django/desafio/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = "desafio"

urlpatterns = [
    path('', views.home_page, name='index'),
    path('add/', views.add, name='add'),
    path('list/', views.list, name='list'),
    path('remove/', views.remove, name='remove'),
    path('removeCamera/<int:id>', views.remove_camera, name='removeCamera'),

    # API
    path('cameras/', views.CameraList.as_view()),
    path('cameras/<int:pk>/', views.CameraDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

django/octos/urls.py
from django.urls import path, include
# from django.contrib import admin

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include("desafio.urls")),
]

django/desafio/models.py
from django.db import models

# Create your models here.


class SerieField(models.CharField):
    def to_python(self, value):
        return value.upper()


class Camera(models.Model):
    FABRICANTES = (
        ('Secure Câmeras Inc', 'Secure Câmeras Inc'),
        ('Surveillance Cams LLC', 'Surveillance Cams LLC'),
        ('DigiEye Group', 'DigiEye Group'),
        ('CâmeraFi Inc', 'CâmeraFi Inc'),
        ('VidMasters Inc', 'VidMasters Inc')
    )

    nome = models.CharField(max_length=50, default='nome')
    fabricante = models.CharField(max_length=50,
                                  default='fabricante',
                                  choices=FABRICANTES)
    serie = SerieField(max_length=16, default='serie', unique=True)

    # python 3
    def __str__(self):
        return self.nome

    # python 2
    def __unicode__(self):
        return self.nome

django/desafio/forms.py
from django import forms


class SerieField(forms.CharField):
    def to_python(self, value):
        return value.upper()


FABRICANTES = (
    ('', 'Selecione o fabricante...'),
    ('Secure Câmeras Inc', 'Secure Câmeras Inc'),
    ('Surveillance Cams LLC', 'Surveillance Cams LLC'),
    ('DigiEye Group', 'DigiEye Group'),
    ('CâmeraFi Inc', 'CâmeraFi Inc'),
    ('VidMasters Inc', 'VidMasters Inc')
)


class AddForm(forms.Form):
    nome = forms.CharField(label='Nome da Câmera:',
                           max_length=50,
                           widget=forms.TextInput(attrs={'placeholder': 'ex: Hall de Entrada.'}),
                           required=True)
    serie = SerieField(label='Número de Série:',
                       max_length=16,
                       widget=forms.TextInput(attrs={'placeholder': 'Apenas caracteres maiúsculos e números, sem espaço.'}),
                       required=True)
    fabricante = forms.ChoiceField(widget=forms.Select(),
                                   label='Fabricante:',
                                   choices=FABRICANTES,
                                   required=True)

django/desafio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Camera
from .forms import AddForm
from .serializers import CameraSerializer
from rest_framework import generics


# views da api Rest
class CameraList(generics.ListCreateAPIView):
    queryset = Camera.objects.all()
    serializer_class = CameraSerializer


class CameraDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Camera.objects.all()
    serializer_class = CameraSerializer


# views do frontend
def home_page(request):
    return render(request, "index.html")


def list(request):
    queryset = Camera.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "list.html", context)


def add(request):
    form = AddForm()
    if(request.method == 'POST'):
        form = AddForm(request.POST)
        if(form.is_valid()):
            camera_nome = form.cleaned_data['nome']
            camera_fabricante = form.cleaned_data['fabricante']
            camera_serie = form.cleaned_data['serie']
            if (Camera.objects.filter(serie=camera_serie).exists()):
                messages.success(request,
                                 'Esse Número de Série já existe! Por favor entre com outro!')
                return redirect('desafio:add')
            else:
                new_camera = Camera(nome=camera_nome,
                                    fabricante=camera_fabricante,
                                    serie=camera_serie)
                new_camera.save()
                return redirect('desafio:list')
    elif(request.method == 'GET'):
        return render(request, 'add.html', {'form': form})


def remove(request):
    queryset = Camera.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "remove.html", context)


def remove_camera(request, id):
    obj = get_object_or_404(Camera, pk=id)
    obj.delete()
    return redirect('desafio:remove')

django/desafio/templates/add.html
<!DOCTYPE html>
<html lang="pt-BR">
 <head>
  <meta charset="UTF-8">
  <title> Adicionar câmera </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 </head>
 <body id="page"> 
   <header id="octos-header">
     <center>
	<img src="{% static 'img/logo.png' %}" alt="Logo">
     </center>
     <div class="titulo">
        Adicionar câmera <br>
     </div>
     {% if messages %}
     {% for message in messages %}
     {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
     {% endfor %}
     {% endif %}
     <button class="btn-page btn-back"><a href="{% url 'desafio:index' %}" style="text-decoration:none"> < Voltar</a></button>
    <br>   
    <br>  
    <br>    
   </header>

{% load crispy_forms_tags %}
{% block content %}
{% if form %}
   <form class="add-form" method="post" action=""> 
        {% csrf_token %}
        {{ form|crispy }}
        <br><input type="submit" class="btn-page" name="btn-add" value="Adicionar">
   </form>
{% endif %}
{% endblock %}

 </body>
</html>

django/desafio/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
 <head>
  <meta charset="UTF-8">
  <title> Desafio Octos </title>
  <meta name="description" content="Desenvolvimento de um sistema web para cadastro de câmeras.">
  <meta name="author" content="Larissa Bral">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
 </head>
 <body id="main-page">
  
   <header id="octos-header">
     <center>
	<img src="{% static 'img/logo.png' %}" alt="Logo">
     </center>
     <nav id="main-nav">
       <ul>
         <li><button class="main-btn btn-green"><a href="{% url 'desafio:add' %}">Adicionar câmera</a></button></li>
         <li><button class="main-btn btn-orange"><a href="{% url 'desafio:list' %}">Listar câmeras</a></button></li>
         <li><button class="main-btn btn-pink"><a href="{% url 'desafio:remove' %}">Remover câmera</a></button></li>
       </ul>
      </nav>
    </header>
  	   
 </body>
</html>

django/desafio/templates/list.html
<!DOCTYPE html>
<html lang="pt-BR">
 <head>
  <meta charset="UTF-8">
  <title> Listar câmeras inseridas</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 </head>
 <body id="page"> 
   <header id="octos-header">
     <center>
	<img src="{% static 'img/logo.png' %}" alt="Logo">
     </center>
     <div class="titulo">
        Listar Câmeras Inseridas <br>
     </div>
     <button class="btn-page btn-back"><a href="{% url 'desafio:index' %}" style="text-decoration:none"> < Voltar</a></button>
     
   </header>
   <br><br>
   <table class="tabela" >
    <tr>
        <td>Nome</td>
        <td>Fabricante</td>
        <td>Número de Série</td>
    </tr>
{% for obj in object_list %}
    <tr>
        <td>{{ obj.nome }} </td>
        <td>{{ obj.fabricante }}</td>
        <td>{{ obj.serie }}</td>

    </tr>
{% endfor%}
   </table>


 </body>
</html>

django/desafio/templates/remove.html
<!DOCTYPE html>
<html lang="pt-BR">
 <head>
  <meta charset="UTF-8">
  <title> Remover câmera </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 </head>
 <body id="page"> 
   <header id="octos-header">
     <center>
	<img src="{% static 'img/logo.png' %}" alt="Logo">
     </center>
     <div class="titulo">
        Remover câmera <br>
     </div>
     <button class="btn-page btn-back"><a href="{% url 'desafio:index' %}" style="text-decoration:none"> < Voltar</a></button>
     
   </header>
   <br><br>
   <nav id="instaled-cameras">
   <ul>
      
      <li>   
      <span> 
    	<table class="tabela" >
  	    <tr>
	        <td>Nome</td>
	        <td>Fabricante</td>
	        <td>Número de Série</td>
                <td>Remover Câmera</td>
	    </tr>

	    <tr>
	    {% for obj in object_list %}
	        <td>{{ obj.nome }} </td>
	        <td>{{ obj.fabricante }}</td>
	        <td>{{ obj.serie }}</td>
                <td><a class ="btn btn-lg" href="{% url 'desafio:index' %}removeCamera/{{obj.id}}"><span>
                    <i class="glyphicon glyphicon-trash" style="color:red"></i></span></a>
                    </td>
	    </tr>
	    {% endfor%}
	</table> 
      </span>
      
      </li>
      
   </ul>
   </nav>
 </body>
</html>